[package]
name = "sidereal-time"
version = "0.1.0"
edition = "2018"
authors = ["TigerInYourDreams <zyzzz0928@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
chrono = "0.4"